### ISSUE TITLE
Yeoman generator failure

### ISSUE THREAD

**Issue by merriam** [hung-phan/generator-rails-react-webpack#7]
Installing looks for a Gemfile in the top level?

```
$ yo
? 'Allo Charles! What would you like to do? Rails React Webpack

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo rails-react-webpack

? What css library would you like to include? Animate SCSS, Bootstrap font-awesome
? What tool support would you like to include? Grape Rest, therubyracer, Livereload
? What js library would you like to include? Lodash.js, REST superagent by visionmedia, Modernizr
Processing Gemfile
identical tmp/yeoman/Gemfile

     _-----_
    |       |    .----------------------.
    |--(o)--|    |     Bye from us!     |
   `---------´   |      Chat soon.      |
    ( _´U`_ )    |      Yeoman team     |
    /___A___\    |   http://yeoman.io   |
     |  ~  |     '----------------------'
   __'.___.'__
 ´   `  |° ´ Y `

fs.js:565
fs.write = function(fd, buffer, offset, length, position, callback) {
                                                 ^
Error: ENOENT, no such file or directory '/Users/charlesmerriam/p/react-tut2/Gemfile'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at readFileAsString (/usr/local/lib/node_modules/generator-rails-react-webpack/node_modules/yeoman-generator/lib/actions/wiring.js:275:13)
    at module.exports.yeoman.generators.Base.extend.gemfile (/usr/local/lib/node_modules/generator-rails-react-webpack/app/index.js:105:23)
    at /usr/local/lib/node_modules/generator-rails-react-webpack/node_modules/yeoman-generator/lib/base.js:341:43
    at /usr/local/lib/node_modules/generator-rails-react-webpack/node_modules/yeoman-generator/node_modules/async/lib/async.js:551:21
    at /usr/local/lib/node_modules/generator-rails-react-webpack/node_modules/yeoman-generator/node_modules/async/lib/async.js:227:13
    at iterate (/usr/local/lib/node_modules/generator-rails-react-webpack/node_modules/yeoman-generator/node_modules/async/lib/async.js:134:13)
    at /usr/local/lib/node_modules/generator-rails-react-webpack/node_modules/yeoman-generator/node_modules/async/lib/async.js:145:25
```

**Comment by hung-phan** [comment]
Hi @merriam, is `react-tut2` your Rails project? That means you have initialise your project with following command `rails new my-app --skip-bundle` before running `yo rails-react-webpack`.
